[versions]
bundletool = "1.13.2"
# Keep this values in sync with bundletool"s dependencies.
aapt2Proto = "7.3.0-alpha07-8248216"
protobufJava = "3.19.2"
guava = "31.0.1-jre"

dalvikdx = "11.0.0_r3"
apkparser = "30.3.1"
apksign = "7.3.1"
clikt = "3.5.1"
junit = "5.9.1"
okio = "3.2.0"
byteunits = "0.9.1"
asm = "9.4"
javaDiffUtils = "4.12"
picnic = "0.6.0"
kotlin = "1.7.22"
kotlinter = "3.13.0"
r8 = "3.3.75"
assertJ = "3.23.1"

[libraries]
dalvikDx = { module = "com.jakewharton.android.repackaged:dalvik-dx", version.ref = "dalvikdx" }
binaryResources = { module = "com.android.tools.apkparser:binary-resources", version.ref = "apkparser" }
apkSigner = { module = "com.android.tools.build:apksig", version.ref = "apksign" }
bundleTool = { module = "com.android.tools.build:bundletool", version.ref = "bundletool" }
aapt2Proto = { module = "com.android.tools.build:aapt2-proto", version.ref = "aapt2Proto" }
protobufJava = { module = "com.google.protobuf:protobuf-java", version.ref = "protobufJava" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
assertJ = { module = "org.assertj:assertj-core", version.ref = "assertJ" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
byteunits = { module = "com.jakewharton.byteunits:byteunits", version.ref = "byteunits" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
diffUtils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "javaDiffUtils" }
picnic = { module = "com.jakewharton.picnic:picnic", version.ref = "picnic" }
r8 = { module = "com.android.tools:r8", version.ref = "r8" }

[plugins]
jmailen-kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
kotlin-dokka = { id = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
